### ISSUE TITLE
Server Finder Broken

### ISSUE THREAD

**Issue by Paupstar** [ynk/LolAccountManager#1]
I changed my hashtag and as a result it displays the wrong server. 
![image](https://user-images.githubusercontent.com/88709309/128833315-899afd46-6190-4dd1-9db6-2e22809275b8.png)

**Comment by ynk** [comment]
Interesting, I will try this out myself and see if I can find a fix for it.  :)

**Comment by ynk** [comment]
Please use the latest release, I have fixed the issue.

https://github.com/ynk/LolAccountManager/releases/tag/V1.1
